title                    : "Zhen Yang (杨振)"
description              : "Cease to struggle and you cease to live."
repository               : "MichaelYeung2004/michaelyeung2004.github.io"
google_scholar_stats_use_cdn : true

url                      : "https://michaelyeung2004.github.io"
baseurl                  : ""

google_analytics_id      :
google_site_verification :
bing_site_verification   :
baidu_site_verification  :

author:
  name             : "Zhen Yang (杨振)"
  avatar           : "assets/images/photos/yangzhen-optimized.jpg"
  bio              : "Institute of Computing Technology, Chinese Academy of Sciences"
  location         : "Beijing, China"
  employer         :
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=tHhfOMoAAAAJ&hl=en"
  email            : "yangzh273@mail2.sysu.edu.cn"
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "MichaelYeung2004"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "zhen-yang-034192314"
  dblp             :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : "AliceDeRoss2"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - _blogs
  - _news
  - _publications
  - _showcase
  - blogs.html
  - index_layout2.html
  - publications.html
  - showcase.html
  - test.md
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
